name: Java CD with Yandex Compute Cloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: topblog-app
          path: target/*.jar
      - name: Download artifact for deployment job
        uses: actions/download-artifact@v3
        with:
          name: topblog-app
      - name: Kill old app
        run: pgrep java | xargs kill -9
      - name: Run new app
        run: nohup java -jar topblog-app-0.0.1.jar > log.txt &
